In [78]:
## import the libraries
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder




In [79]:
## load the dataset
train_titanic = pd.read_csv('train.csv')
test_titanic = pd.read_csv('test.csv')

In [80]:
train_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [81]:
test_titanic.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [82]:
## train, test and split
X_train = train_titanic.drop('Survived', axis=1)
y_train = train_titanic['Survived']

In [83]:
## scale to range
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler, KBinsDiscretizer, LabelEncoder, OneHotEncoder

## load the iris dataset
iris = load_iris()
X = iris.data 

In [84]:
Minimum = -1
Maximum = 1

In [85]:
## create an instance for my minmaxscaler
scaler = MinMaxScaler(feature_range=(Minimum, Maximum))
scaled_data = scaler.fit_transform(X)

In [86]:
## ORIGINAL DATA
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [87]:
## SCALED DATA
scaled_data[:5]

array([[-0.55555556,  0.25      , -0.86440678, -0.91666667],
       [-0.66666667, -0.16666667, -0.86440678, -0.91666667],
       [-0.77777778,  0.        , -0.89830508, -0.91666667],
       [-0.83333333, -0.08333333, -0.83050847, -0.91666667],
       [-0.61111111,  0.33333333, -0.86440678, -0.91666667]])

In [88]:
## create an instance
rob_scaler = RobustScaler()

## FIT AND TRANSFORM THE DATA
scaler_data = rob_scaler.fit_transform(X)


In [89]:
scaler_data[:5]

array([[-0.53846154,  1.        , -0.84285714, -0.73333333],
       [-0.69230769,  0.        , -0.84285714, -0.73333333],
       [-0.84615385,  0.4       , -0.87142857, -0.73333333],
       [-0.92307692,  0.2       , -0.81428571, -0.73333333],
       [-0.61538462,  1.2       , -0.84285714, -0.73333333]])

In [90]:
## feature clipping
## set up a range to clip our features
min_clip = 0
max_clip = 2
## clip the features
clipped_features = np.clip(X, min_clip, max_clip)

In [91]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [92]:
clipped_features[:5]

array([[2. , 2. , 1.4, 0.2],
       [2. , 2. , 1.4, 0.2],
       [2. , 2. , 1.3, 0.2],
       [2. , 2. , 1.5, 0.2],
       [2. , 2. , 1.4, 0.2]])

In [93]:
##LOG SCALING
log_scaled = np.log(X)
log_scaled[:5]

array([[ 1.62924054,  1.25276297,  0.33647224, -1.60943791],
       [ 1.58923521,  1.09861229,  0.33647224, -1.60943791],
       [ 1.54756251,  1.16315081,  0.26236426, -1.60943791],
       [ 1.5260563 ,  1.13140211,  0.40546511, -1.60943791],
       [ 1.60943791,  1.28093385,  0.33647224, -1.60943791]])

In [94]:
## zscore/ standard scaler
std_scaler = StandardScaler()
## FIT AND TRANFORM THE DATA
scaler_z = std_scaler.fit_transform(X)
scaler_z[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [95]:
## load the dataframe
data = pd.DataFrame(iris.data, columns=iris.feature_names)

## create a bucket
number_bucket = 5
## initialize the instance of the kbinsdiscretizer
dis = KBinsDiscretizer(n_bins=number_bucket, encode='ordinal', strategy='uniform')


## fit and transform the data
trans_dis = pd.DataFrame(dis.fit_transform(data), columns = data.columns)

trans_dis.head(5)


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                1.0               3.0                0.0               0.0
1                0.0               2.0                0.0               0.0
2                0.0               2.0                0.0               0.0
3                0.0               2.0                0.0               0.0
4                0.0               3.0                0.0               0.0

In [96]:
## load the dataframe
data = pd.DataFrame(iris.data, columns=iris.feature_names)

## create a bucket
number_bucket = 5
## initialize the instance of the kbinsdiscretizer
dis = KBinsDiscretizer(n_bins=number_bucket, encode='ordinal', strategy='quantile')


## fit and transform the data
trans_dis = pd.DataFrame(dis.fit_transform(data), columns = data.columns)

trans_dis.head(5)


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                1.0               4.0                0.0               1.0
1                0.0               2.0                0.0               1.0
2                0.0               3.0                0.0               1.0
3                0.0               3.0                1.0               1.0
4                1.0               4.0                0.0               1.0

In [97]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [98]:
test_titanic.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [99]:
## label encoder
## declare an instance
le = LabelEncoder()
test_titanic['Sex_encoded'] = le.fit_transform(test_titanic['Sex'])


In [100]:
test_titanic.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Sex_encoded  
0  34.5      0      0   330911   7.8292   NaN        Q            1  
1  47.0      1      0   363272   7.0000   NaN        S            0  
2  62.0      0      0   240276   9.6875   NaN        Q            1  
3  27.0      0      0   315154   8.6625   NaN        S            1  
4  22.0      1      1  3101298  12.2875   NaN        S            0

In [101]:
## get dummies
new_sex = pd.get_dummies(train_titanic['Sex'])

## concatenate
train_titanic = pd.concat([train_titanic, new_sex], axis=1)

## drop the old column of sex
train_titanic.drop(columns=['Sex'], inplace=True)

In [102]:
train_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0   
2                             Heikkinen, Miss. Laina  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0   
4                           Allen, Mr. William Henry  35.0      0      0   

             Ticket     Fare Cabin Embarked  female   male  
0         A/5 21171   7.2500   NaN        S   False   True  
1          PC 17599  71.2833   C85        C    True  False  
2  STON/O2. 3101282   7.9250   NaN        S    True  False  
3            113803  53.1000  C123        S    True  False  
4            373450   8.0500   NaN        S   False   True

In [103]:
## one hot encoder
## create an instance of the one hot encoder
ohe = OneHotEncoder(handle_unknown='ignore', sparse=False)

## fit and transform
ohe_transform = ohe.fit_transform(test_titanic[['Embarked']])


## create a dataframe from the array that wull be gebarated above
ohe_df = pd.DataFrame(ohe_transform, columns = ohe.get_feature_names_out(['Embarked']))


## concatenate
test_titanic = pd.concat([test_titanic, ohe_df], axis=1)

## drop the embarked column

test_titanic.drop(columns=['Embarked'], inplace=True)

test_titanic.head()

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [ ]:
import sklearn
print(sklearn.__version__)


1.4.0


In [ ]:
train_titanic['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [ ]:
## decomposing the data
new_data = pd.DataFrame({'datetime': ['2024-01-01 10:30:00', '2024-10-01 12:30:59']})

## convert this to datetime

new_data['datetime'] = pd.to_datetime(new_data['datetime'])

## split the date time
new_data['year'] = new_data['datetime'].dt.year
new_data['month'] = new_data['datetime'].dt.month
new_data['hour'] = new_data['datetime'].dt.hour
new_data['day_name'] = new_data['datetime'].dt.day_name()

new_data

datetime  year  month  hour day_name
0 2024-01-01 10:30:00  2024      1    10   Monday
1 2024-10-01 12:30:59  2024     10    12  Tuesday

In [ ]:
X = pd.DataFrame(iris.data, columns = iris.feature_names)

In [ ]:
CORR = X.corr()
CORR

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000

In [ ]:
## feature selection
corr_mat = X.corr().abs()
## created a matrix of ones with the same shape with corr mat
mask = np.triu(np.ones_like(corr_mat, dtype=bool))

mask_df = corr_mat.mask(mask)

mask_df

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)                NaN               NaN                NaN   
sepal width (cm)            0.117570               NaN                NaN   
petal length (cm)           0.871754          0.428440                NaN   
petal width (cm)            0.817941          0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)               NaN  
sepal width (cm)                NaN  
petal length (cm)               NaN  
petal width (cm)                NaN

In [ ]:
drop_it = [c for c in mask_df.columns if any(mask_df[c] > 0.95)]

drop_it

['petal length (cm)']

In [ ]:
reduced_df = X.drop(drop_it, axis=1)
reduced_df

sepal length (cm)  sepal width (cm)  petal width (cm)
0                  5.1               3.5               0.2
1                  4.9               3.0               0.2
2                  4.7               3.2               0.2
3                  4.6               3.1               0.2
4                  5.0               3.6               0.2
..                 ...               ...               ...
145                6.7               3.0               2.3
146                6.3               2.5               1.9
147                6.5               3.0               2.0
148                6.2               3.4               2.3
149                5.9               3.0               1.8

[150 rows x 3 columns]

In [ ]:
## pca
from sklearn.decomposition import PCA

## CREATE AN INSTANCE
pca = PCA(n_components=3)

X_pca = pca.fit_transform(X)

In [ ]:
X_pca[:5]

array([[-2.68412563],
       [-2.71414169],
       [-2.88899057],
       [-2.74534286],
       [-2.72871654]])

In [ ]:
## print the ratio
pca.explained_variance_ratio_

array([0.92461872, 0.05306648, 0.01710261])